### ISSUE TITLE
stragglers are not waited

### ISSUE THREAD

**Issue by photoszzt** [excamera/pipeline#4]
https://github.com/excamera/pipeline/blob/64709f3904981f74511b61266b30f2625606055c/sprocket/controlling/common/handler.py#L316-L333

On line 316, the res is never used. Should that line be results.wait()? upload also doesn't return anything.
On line 333, there's nothing wait on res. The straggler mitigation are never waited? Should it be results not res?

**Comment by lihshyang** [comment]
Yes, you're right. The `get()` and `wait()` are basically equivalent since nothing is really to be returned.

On line 333, we don't have to explicitly `wait()` because the `upload(f)` callback will mark the completion of file uploading in the `finished` dictionary. `finished` is checked in every loop on line 323.

**Comment by photoszzt** [comment]
@lihshyang I see. Thanks for the reply.
